spring:
  application:
    name: library-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:library}
    username: ${DB_USER:library}
    password: ${DB_PASSWORD:library}
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:\n    show-sql: true\n    hibernate:\n      ddl-auto: validate\n    properties:\n      hibernate:\n        format_sql: true\n    open-in-view: false

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO\n    org.springframework.security: DEBUG\n    ru.synergy.libraryapp: DEBUG\n    org.hibernate.SQL: DEBUG\n    org.hibernate.orm.jdbc.bind: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info

